- name: Install nginx
  ansible.builtin.apt:
    name: nginx

- name: Configure nginx frontend service
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true