- name: Install nginx
  ansible.builtin.apt:
    name: nginx

- name: Configure nginx frontend service
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx


# integrate prometheus to nginx

- name: Install prometheus-nginx-exporter
  apt:
    name: prometheus-nginx-exporter
  notify: Restart nginx-exporter

- name: Start nginx and exporter
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter