- name: Install nginx
  ansible.builtin.apt:
    name: nginx

- name: Configure nginx frontend service
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true


# integrate prometheus to nginx

- name: Install prometheus-nginx-exporter
  apt:
    name: prometheus-nginx-exporter
  notify: Restart nginx-exporter
