# Manage DNS settings manually

- name: Stop systemd-resolved
  service:
    name: systemd-resolved
    state: stopped

- name: Change resolv.conf content
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf