- name: Download influxdb
  get_url:
   url: "https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb"
   dest: "/tmp/influxdb_1.8.10_amd64.deb"

- name: Install influxdb
  apt:
   deb: "/tmp/influxdb_1.8.10_amd64.deb"

- name: Activate influxdb
  service:
    name: influxdb
    state: started
    enabled: true