- name: Install Grafana via Docker
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    volumes: /opt/grafana:/etc/grafana
    

- name: Create volume directories
  ansible.builtin.file:
    path: /opt/grafana/provisioning/{{ item }}
    state: directory
  loop:
    - dashboards
    - datasources

- name: Copy grafana configs to volume
  template:
    src: grafana.ini
    dest: /opt/grafana/grafana.ini
  notify: Restart grafana

- name: Copy dashboards config to volume
  copy:
    src: dashboards.yaml
    dest: /opt/grafana/provisioning/dashboards/dashboards.yaml
  notify: Restart grafana

- name: Copy datasources config to volume
  copy:
    src: dataSources.yaml
    dest: /opt/grafana/provisioning/datasources/dataSources.yaml
  notify: Restart grafana

- name: Copy all dashboards to volume
  copy:
    src: "{{ item }}"
    dest: /opt/grafana/provisioning/dashboards/{{ item }}
  loop:
    - main.json
    - mysql.json
    - syslog.json
  notify: Restart grafana
