- name: Install uwsgi
  ansible.builtin.apt:
    name: uwsgi

- name: Install uwsgi-plugin-python3
  ansible.builtin.apt:
    name: uwsgi-plugin-python3

- name: Create uwsgi config file
  ansible.builtin.template:
    src: agama.ini.j2 
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0600
  no_log: true
  notify: Restart uwsgi

- name: Start uwsgi service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true