---
- name: Initial setup
  hosts: all
  roles:
    - role: init
      tags: init

- name: Prometheus server
  hosts: prometheus_servers
  roles:
    - role: prometheus
      tags: pro

- name: Database server
  hosts: db_servers
  roles:
    - role: mysql
      tags: db

- name: Bind server
  hosts: bind_servers
  roles:
    - role: bind
      tags: bind

- name: influxDB server
  hosts: influxdb_servers
  roles:
    - role: influxdb
      tags: in

- name: Pinger server
  hosts: pinger_servers
  roles:
    - role: pinger
      tags: ping

- name: Grafana server
  hosts: grafana_servers
  roles:
    - role: grafana
      tags: gra

- name: Configure DNS settings for both
  hosts: all
  roles:
    - role: config-dns
      tags: dns

- name: Web server
  hosts: web_servers
  roles:
    - role: agama
      tags: aga
    
    - role: uwsgi
      tags: uw

    - role: nginx
      tags: ng
