{
 "title": "Main",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[10m])) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bind9 Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{job=\"linux\"}[10m]) + avg_over_time(node_memory_Cached_bytes{job=\"linux\"}[10m]) + avg_over_time(node_memory_Buffers_bytes{job=\"linux\"}[10m])) / avg_over_time(node_memory_MemTotal_bytes{job=\"linux\"}[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Queries ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "idelta(bind_resolver_queries_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "idelta(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SELECT Queries ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "idelta(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}