- name: Create agama volume directory
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Download agama files
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}
    dest: /opt/agama/{{ item }}
  loop:
    - agama.py
    - Dockerfile

- name: Create agama docker container
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Start agama docker container
  community.docker.docker_container:
    name: agama
    image: agama
    published_ports: "{{ agama_port }}:8000"
    env:
       AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
  no_log: true