# Install mysql and change its config files

- name: Install mysql
  ansible.builtin.apt:
    name: mysql-server

- name: Listen public
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart mysql

- name: Start mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

# Configure mysql

- name: Install python3-pymysql
  ansible.builtin.apt:
    name: python3-pymysql

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

# Configure user settings

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock 

# mysql prometheus integration

- name: Configure mysql exporter credentials
  template:
    src: my.conf.j2
    dest: /var/lib/prometheus/.my.cnf
  no_log: true
  notify: Restart mysql-exporter

- name: Create mysql exporter user
  community.mysql.mysql_user:
    name: "{{mysql_exporter_user}}"
    password: "{{mysql_exporter_password}}"
    host: "%"
    resource_limits:
      MAX_USER_CONNECTIONS: 3
    priv: "*.*:PROCESS/*.*:REPLICATION CLIENT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart mysql-exporter

- name: Install prometheus-mysqld-exporter
  apt: 
    name: prometheus-mysqld-exporter

- name: Create backup directory for mysql
  file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    group: backup
    mode: 0660

