- name: Install mysql
  ansible.builtin.apt:
    name: mysql-server

- name: Start mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Listen public
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart mysql