- name: Install Prometheus
  apt:
    name: prometheus

# add prefix web.external-url... to get a correct redirection url from http://.../prometheus
- name: Adjust Prometheus service
  template:
    src: prometheus
    dest: /etc/default/prometheus
  notify: Restart Prometheus

- name: Add data source VMs
  template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus

- name: Start prometheus
  service:
    name: prometheus
    state: started
    enabled: true

- name: Add prometheus A record
  include_role:
    name: dns_record
    tasks_from: add_dns_records
  vars:
    record: "prometheus"
    value: "{{ groups['prometheus_servers'][0] }}"
    type: "CNAME"