- name: Install bind9
  apt:
    name: bind9

- name: Configure bind9 files
  template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
    # validate: /usr/sbin/named-checkconf %s
  loop:
    - options
    - local
  notify: Restart bind9
  no_log: true

- name: Configure master zone
  template:
    src: zone.j2
    dest: /var/cache/bind/db.{{ domain_name }}
    force: false
  notify: Restart bind9
  when: inventory_hostname in groups ['bind_masters']

# Export bind logs to prometheus
- name: Install prometheus-bind-exporter
  apt:
    name: prometheus-bind-exporter

- name: Start bind9 and exporter
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - bind9
    - prometheus-bind-exporter

- name: Install dnspython
  apt:
    name: python3-dnspython
  when: inventory_hostname in groups ['bind_masters']

- name: Run handlers
  meta: flush_handlers

# - name: Add A records
#   community.general.nsupdate:
#     key_algorithm: "hmac-sha256" 
#     key_name: "nsupdate.key"
#     key_secret: "{{ dns_nsupdate_secret }}"
#     server: "{{ item.1 }}"
#     record: "{{ item.0.key }}"
#     value: "{{ item.0.value }}"
#     zone: "{{ domain_name }}"
#   loop: "{{ a_records | map('dict2items') | flatten | zip(groups['bind_masters'])}}"
#   when: inventory_hostname in groups ['bind_masters']

- name: Debug
  debug:
    var: hostvars[master]['ansible_default_ipv4']['address']
  loop: "{{ groups['bind_masters'] }}"
  loop_control:
    loop_var: master 

- name: Add A records
  include_role:
    name: dns_record
    tasks_from: add_dns_records
  vars:
    record: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "A"
  loop: "{{ a_records | map('dict2items') | flatten }}"


- name: Add NS records
  include_role:
    name: dns_record
    tasks_from: add_dns_records
  vars:
    record: "ns-{{server_index + 1}}"
    value: "{{ item }}"
    type: "CNAME"
  loop: "{{ groups['bind_servers'] }}"
  loop_control:
    index_var: server_index