- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Download certificates
  apt:
    name: ca-certificates=20230311ubuntu0.20.04.1
    update_cache: true

# Install Prometheus Node Exporters

- name: Install prometheus node exporter
  apt:
    name: prometheus-node-exporter

- name: Modify rsyslog conf file
  copy:
    src: rsyslog-tel.conf
    dest: /etc/rsyslog.d/tel.conf
  notify: Restart rsyslog

- name: Create backup user
  user:
    name: backup
    home: /home/backup
    generate_ssh_key: true
    ssh_key_file: /home/backup/.ssh/id_rsa

- name: Add backup server to known hosts
  template:
    src: known_hosts
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: 0600

# set up backup

- name: Create restore directory 
  file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: 0777

- name: Install duplicity
  apt:
    name: duplicity


- name: Install dnspython
  apt:
    name: python3-dnspython