# - name: Ansible ping module
#  ansible.builtin.ping:
  
# - name: Create juri
#   ansible.builtin.user:
#     name: juri

# - name: Set authorized public keys juri
#   ansible.posix.authorized_key:
#     user: juri
#     key: https://github.com/hudolejev.keys

# - name: Create roman
#   ansible.builtin.user: 
#     name: roman

# - name: Set authorized public keys roman
#   ansible.posix.authorized_key:
#     user: roman
#     key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400


# Manage DNS settings manually

- name: Stop systemd-resolved
  service:
    name: systemd-resolved
    state: stopped

- name: Change resolve.conf content
  template:
    src: resolve.conf.j2
    dest: /etc/resolv.conf